services:
  db:
    image: postgres:16
    container_name: neurona-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patientsdb
    ports:
      - "5438:5432"    # <<< DŮLEŽITÉ – host:container
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Neurona.Health.Api/Dockerfile
    container_name: neurona-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # pokud v appsettings.json používáš ConnectionStrings:DefaultConnection,
      # můžeš ji přepsat proměnnou prostředí:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5437;Database=patientsdb;Username=postgres;Password=postgres"
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile   # nebo 'Dockerfile', pokud přejmenuješ
    container_name: neurona-frontend
    environment:
      NEXT_PUBLIC_GRAPHQL_ENDPOINT: "http://api:8080/graphql"
    depends_on:
      - api
    ports:
      - "3001:3000"

volumes:
  db-data:
